source ~/.config/nvim/init/plugged.vim
source ~/.config/nvim/init/options.vim
source ~/.config/nvim/init/theme.vim
source ~/.config/nvim/init/plugin_nerdtree.vim
source ~/.config/nvim/init/plugin_nerdtree-tabs.vim
source ~/.config/nvim/init/plugin_airline.vim
source ~/.config/nvim/init/plugin_better-whitespace.vim
source ~/.config/nvim/init/plugin_ctrlp.vim
source ~/.config/nvim/init/plugin_ctrlsf.vim
source ~/.config/nvim/init/plugin_eighties.vim
source ~/.config/nvim/init/plugin_gina.vim
source ~/.config/nvim/init/plugin_indent-guides.vim
source ~/.config/nvim/init/plugin_prettier.vim
source ~/.config/nvim/init/plugin_simple-snippets.vim
source ~/.config/nvim/init/plugin_split-term.vim
source ~/.config/nvim/init/plugin_table-mode.vim
source ~/.config/nvim/init/plugin_tagbar.vim
source ~/.config/nvim/init/plugin_ultisnips.vim
source ~/.config/nvim/init/plugin_quickui.vim
source ~/.config/nvim/init/plugin_omnisharp.vim
source ~/.config/nvim/init/plugin_ale.vim
source ~/.config/nvim/init/plugin_syntastic.vim
source ~/.config/nvim/init/plugin_asyncomplete.vim
source ~/.config/nvim/init/plugin_sharpenup.vim
source ~/.config/nvim/init/plugin_fzf.vim

source ~/.config/nvim/init/shortcuts.vim
